
const subCategory = [
    {
      categoryName: 'NEW',
      subCategories: [
        { name: "VIEW ALL", active: false },
        { name: "PILLOWS & THROWS", active: false },
        { name: "APRIL ARRIVALS", active: false },
        { name: "FURNITURE", active: false },
        { name: "BEDDING & BATH", active: false },
        { name: "SOFAS UNDER $1500", active: false },
        { name: "LIGHTING", active: false },
        { name: "RUGS", active: false },
        { name: "KITCHEN & DINING", active: false },
        { name: "BEDDING & BATH", active: false },
        { name: "OUR FAVORITES", active: false },
        { name: "DINING TABLES", active: false },
        { name: "DINING CHAIRS", active: false },
        { name: "OUTDOOR", active: false },
        { name: "DECOR & MIRRORS", active: false },
        { name: "LIGHTING", active: false },
        { name: "OUR FAVORITES", active: false },
        { name: "NEW DECOR UNDER $100", active: false },
        { name: "NEW 8'X10' RUGS", active: false },
        { name: "NEW ORGANIC COTTON BEDDING", active: false },
        { name: "2023 NEXT IN DESIGN", active: false },
        { name: "OUTDOOR COLLECTION BY ROSS CASSIDY", active: false },
        { name: "BEDDING & BATH", active: false },
        { name: "FREE DESIGN SERVICES", active: false },
      ]
    },
    {
      categoryName: "FURNITURE",
      subCategories: [
        { name: "VIEW ALL", active: false },
        { name: "SOFAS", active: false },
        { name: "SECTIONALS", active: false },
        { name: "SLEEPERS & DAYBEDS", active: false },
        { name: "ACCENT CHAIRS", active: false },
        { name: "ACCENT CHAIR SETS", active: false },
        { name: "BENCHES", active: false },
        { name: "IN-STOCK", active: false },
        { name: "COFFEE TABLES", active: false },
        { name: "SIDE TABLES", active: false },
        { name: "CONSOLE TABLES", active: false },
        { name: "BEDS", active: false },
        { name: "NIGHTSTANDS", active: false },
        { name: "DRESSERS & CHESTS", active: false },
        { name: "WARDROBES & CHIFFEROBES", active: false },
        { name: "BEDROOM BENCHES", active: false },
        { name: "MATTRESSES & FOUNDATIONS", active: false },
        { name: "MEDIA CONSOLES", active: false },
        { name: "STORAGE CABINETS", active: false },
        { name: "BOOKCASES", active: false },
        { name: "ENTRYWAY STORAGE", active: false },
        { name: "DESKS", active: false },
        { name: "OFFICE CHAIRS", active: false },
        { name: "TRAVERTINE AND UNIQUE MARBLES", active: false },
      ]
    },
    {
      categoryName: "OUTDOOR",
      subCategories: [
        { name: "IN-STOCK", active: false },
        { name: "VIEW ALL", active: false },
        { name: "OUTDOOR SOFAS & SECTIONALS", active: false },
        { name: "OUTDOOR LOUNGE CHAIRS & CHAISES", active: false },
        { name: "OUTDOOR COFFEE TABLES", active: false },
        { name: "OUTDOOR SIDE TABLES", active: false },
        { name: "OUTDOOR OTTOMANS & POUFS", active: false },
        { name: "OUTDOOR DINING CHAIR SETS", active: false },
        { name: "OUTDOOR THROW PILLOWS", active: false },
        { name: "OUTDOOR LIGHTING", active: false },
        { name: "OUTDOOR UMBRELLAS", active: false },
        { name: "OUTDOOR COVERS", active: false },
        { name: "BEST SELLERS", active: false },
        { name: "OUTDOOR LOUNGE CHAISES", active: false },
        { name: "PAUL MCCOBB OUTDOOR COLLECTION", active: false },
        { name: "CLEARANCE OUTDOOR", active: false },
        { name: "UP TO 25% OFF SELECT OUTDOOR FURNITURE & DECOR", active: false },
        { name: "PLANTERS UNDER $100", active: false },
      ]
    },
    {
      categoryName: "DECOR & MIRRORS",
      subCategories: [
        { name: "IN-STOCK", active: false },
        { name: "VIEW ALL", active: false },
        { name: "SOFAS", active: false },
        { name: "SECTIONALS", active: false },
        { name: "SLEEPERS & DAYBEDS", active: false },
        { name: "ACCENT CHAIRS", active: false },
        { name: "WALL MIRRORS", active: false },
        { name: "FLOOR MIRRORS", active: false },
        { name: "VANITY MIRRORS", active: false },
        { name: "INFINITY MIRROR COLLECTION", active: false },
        { name: "CANDLE HOLDERS", active: false },
        { name: "CANDLES & HOME FRAGRANCES", active: false },
        { name: "VASES", active: false },
        { name: "PLANTERS", active: false },
        { name: "BOTANICALS", active: false },
        { name: "DECORATIVE BOWLS", active: false },
        { name: "DECORATIVE OBJECTS", active: false },
        { name: "TRAYS", active: false },
        { name: "FIREPLACE ACCESSORIES", active: false },
        { name: "PET ACCESSORIES", active: false },
        { name: "LIMITED EDITION ART", active: false },
        { name: "MODERN ART PRINTS", active: false },
        { name: "ART PATRON", active: false },
        { name: "PICTURE FRAMES", active: false },
      ]
    },
  
  
    {
      categoryName: "LIGHTING",
      subCategories: [
        { name: "VIEW ALL", active: false },
        { name: "TABLE LAMPS", active: false },
        { name: "FLOOR LAMPS", active: false },
        { name: "PENDANT LIGHTS",active: false },
        { name: "FLUSH MOUNTS", active: false },
        { name: "WALL SCONCES", active: false },
        { name: "OUTDOOR LIGHTING", active: false },
        { name: "LIGHTBULBS & SWITCH PLATES", active: false },
        { name: "BEST SELLERS", active: false },
        { name: "CLEARANCE LIGHTING", active: false },
        { name: "THE SPRING EVENT: UP TO 50% OFF SELECT LIGHTING", active: false },
        { name: "LIGHTING UNDER $100", active: false },
        { name: "PENDANT LIGHTS UNDER $500", active: false },
        { name: "MODERN BRASS LIGHTING", active: false },
        { name: "DIMMABLE FLOOR LAMPS", active: false },
        { name: "FARRAH SIT COLLECTION", active: false },
        { name: "STUDIO ANANSI COLLECTION", active: false },
        { name: "FREE DESIGN SERVICES", active: false },
        { name: "", active: false },
        { name: "", active: false },
        { name: "", active: false },
      ]
    },
    {
      categoryName: "RUGS",
      subCategories: [
        { name: "VIEW ALL", active: false },
        { name: "AREA RUGS", active: false },
        { name: "RUNNER RUGS", active: false },
        { name: "ONE-OF-A-KIND RUGS", active: false },
        { name: "DOORMATS", active: false },
        { name: "KITCHEN RUGS", active: false },
        { name: "OUTDOOR RUGS", active: false },
        { name: "BEST SELLERS", active: false },
        { name: "CLEARANCE RUGS", active: false },
        { name: "THE SPRING EVENT: UP TO 50% OFF SELECT RUGS", active: false },
        { name: "8'X10' RUGS UNDER $500", active: false },
        { name: "HOW TO PICK A RUG", active: false },
        { name: "SHOP BY SIZE", active: false },
        { name: "MODERN ABSTRACT RUGS", active: false },
        { name: "HAND KNOTTED RUGS", active: false },
        { name: "STUDIO ANANSI COLLECTION", active: false },
        { name: "FREE DESIGN SERVICES", active: false },
        { name: "", active: false },
      ]
    },
    {
      categoryName: "KITCHEN & DINING",
      subCategories: [
        { name: "VIEW ALL", active: false },
        { name: "DINNERWARE SETS", active: false },
        { name: "SALAD & DINNER PLATES", active: false },
        { name: "FLATWARE", active: false },
        { name: "DRINKING GLASSES", active: false },
        { name: "WINE GLASSES", active: false },
        { name: "COCKTAIL GLASSES", active: false },
        { name: "TEA & COFFEE MUGS", active: false },
        { name: "BAR TOOLS & ACCESSORIES", active: false },
        { name: "PITCHERS & DISPENSERS", active: false },
        { name: "DECANTERS & CARAFES", active: false },
        { name: "DRINK COASTERS", active: false },
        { name: "COFFEE MAKERS & TEAPOTS", active: false },
        { name: "SERVING BOWLS & BASKETS", active: false },
        { name: "CHEESE BOARDS & KNIVES", active: false },
        { name: "SERVING UTENSILS", active: false },
        { name: "KITCHEN STORAGE & ORGANIZATION", active: false },
        { name: "TABLE RUNNERS & TABLECLOTHS", active: false },
      ]
    },
    {
      categoryName: "GIFTS",
      subCategories: [
        { name: "GIFTS", active: false },
        { name: "VIEW ALL GIFTS", active: false },
        { name: "GIFTS UNDER $25", active: false },
        { name: " GIFTS UNDER $50", active: false },
        { name: "GIFTS UNDER $100", active: false },
        { name: "MONOGRAMMED GIFTS", active: false },
        { name: "GAME ROOM GIFTS", active: false },
        { name: "KITCHEN & BAR GIFTS", active: false },
        { name: " BATH & SPA GIFTS", active: false },
        { name: "TECH & OFFICE GIFTS", active: false },
        { name: "HOST GIFTS", active: false },
        { name: "LUXE GIFTS", active: false },
        { name: " SMALL GIFTS", active: false },
        { name: "THANK YOU GIFTS", active: false },
        { name: "WEDDING GIFTS", active: false },
        { name: "GIFT CARD", active: false },
        { name: "WEDDING GIFTS UNDER $100", active: false },
        { name: "GIFTS FOR HER UNDER $50", active: false },
        { name: "GIFTS FOR THE AUDIOPHILE", active: false },
        { name: "FREE DESIGN SERVICES", active: false },
        { name: "SUPRISE", active: false },
      ]
    },
    {
      categoryName: 'SALE',
      subCategories: [
        { name: "SALE", active: false },
        { name: "UP TO 50% OFF SELECT FURNITURE & DECOR", active: false },
        { name: "UP TO 25% OFF SELECT OUTDOOR FURNITURE & DECOR", active: false },
        { name: "ALL CLEARANCE", active: false },
        { name: "CLEARANCE FURNITURE", active: false },
        { name: "CLEARANCE DECOR & MIRRORS", active: false },
        { name: "CLEARANCE LIGHTING", active: false },
        { name: "CLEARANCE PILLOWS & THROWS", active: false },
        { name: "CLEARANCE RUGS", active: false },
        { name: "CLEARANCE KITCHEN & DINING", active: false },
        { name: "CLEARANCE BEDDING & BATH", active: false },
        { name: "CLEARANCE OUTDOOR", active: false },
        { name: "CLEARANCE HOLIDAY", active: false },
        { name: "FREE SHIPPING", active: false },
        { name: "EARN 10% BACK IN REWARD DOLLARS*", active: false },
        { name: "BEDDING SHIPS FREE", active: false },
        { name: "FREE DESIGN SERVICES", active: false },
        { name: "DISCOUNT 35%", active: false },
      ]
    },
  ]
  
  
  
  export default subCategory